# Generated by Django 5.1.4 on 2026-01-05 21:11

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import trainers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الجمعية")),
                ("slug", models.SlugField(unique=True, verbose_name="المعرف")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "established_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التأسيس"
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ الإيجار",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "مجاني"),
                            ("basic", "أساسي"),
                            ("premium", "متميز"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="نوع الاشتراك",
                    ),
                ),
                (
                    "max_trainers",
                    models.IntegerField(
                        default=50, verbose_name="الحد الأقصى للمتدربين"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ناشط")),
                (
                    "trial_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية التجربة"
                    ),
                ),
                (
                    "trial_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="نهاية التجربة"
                    ),
                ),
                (
                    "subscription_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية الاشتراك"
                    ),
                ),
                (
                    "subscription_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="نهاية الاشتراك"
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ بداية الاشتراك"
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ نهاية الاشتراك"
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(default=7, verbose_name="فترة السماح "),
                ),
                (
                    "subscription_period",
                    models.CharField(
                        blank=True,
                        choices=[("1m", "شهر واحد"), ("3m", "ثلاثة أشهر")],
                        max_length=2,
                        null=True,
                        verbose_name="مدة الاشتراك",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ آخر دفعة"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="الموقع"),
                ),
                (
                    "datepay",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ دفع الايجار",
                    ),
                ),
            ],
            options={
                "verbose_name": "جمعية",
                "verbose_name_plural": "الجمعيات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Costs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.CharField(max_length=100, verbose_name="المصروف")),
                ("desc", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="التاريخ")),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="متكرر"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="trainers.organizationinfo",
                        verbose_name="الجمعية",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصروف",
                "verbose_name_plural": "المصاريف",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Addedpay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="العنوان")),
                ("desc", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="التاريخ")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_payments",
                        to="trainers.organizationinfo",
                        verbose_name="الجمعية",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة إضافية",
                "verbose_name_plural": "الدفعات الإضافية",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration_months",
                    models.IntegerField(
                        default=1, help_text="عدد الأشهر التي يغطيها هذا الدفع"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقداً"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("card", "بطاقة"),
                            ("check", "شيك"),
                            ("other", "أخرى"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                            ("semi_annual", "نصف سنوي"),
                            ("annual", "سنوي"),
                            ("custom", "مخصص"),
                        ],
                        default="monthly",
                        max_length=50,
                        verbose_name="فترة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("subscription_start", models.DateField(editable=False)),
                ("subscription_end", models.DateField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_payments",
                        to="trainers.organizationinfo",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت المعالجة بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة اشتراك جمعية",
                "verbose_name_plural": "دفعات اشتراكات الجمعيات",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100, verbose_name="الدور")),
                ("is_admin", models.BooleanField(default=False, verbose_name="مدير")),
                (
                    "started",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ البدء"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الراتب",
                    ),
                ),
                (
                    "datepay",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="trainers.organizationinfo",
                        verbose_name="الجمعية",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفون",
            },
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="الاسم الأول"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="اسم العائلة"),
                ),
                ("birth_day", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="الهاتف"),
                ),
                (
                    "phone_parent",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="هاتف ولي الأمر"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "CIN",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم البطاقة"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=50, verbose_name="العنوان"),
                ),
                (
                    "male_female",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=11,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "belt_degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("أبيض", "أبيض"),
                            ("برتقالي", "برتقالي"),
                            ("أصفر", "أصفر"),
                            ("أصفر مع شريط أخضر", "أصفر مع شريط أخضر"),
                            ("أخضر", "أخضر"),
                            ("أخضر مع شريط أزرق", "أخضر مع شريط أزرق"),
                            ("أزرق", "أزرق"),
                            ("أزرق مع شريط أحمر", "أزرق مع شريط أحمر"),
                            ("أحمر", "أحمر"),
                            ("أحمر مع شريط أسود", "أحمر مع شريط أسود"),
                            ("أسود", "أسود"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="درجة الحزام",
                    ),
                ),
                (
                    "Degree",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="المستوى التعليمي",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("الصغار", "الصغار"),
                            ("فتيان", "فتيان"),
                            ("كبار", "كبار"),
                            ("نساء", "نساء"),
                            ("شبان", "شبان"),
                        ],
                        default="small",
                        max_length=9,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "tall",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الطول",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الوزن",
                    ),
                ),
                (
                    "started_day",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ البدء"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=trainers.models.image_upload_to,
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainers",
                        to="trainers.organizationinfo",
                        verbose_name="الجمعية",
                    ),
                ),
            ],
            options={
                "verbose_name": "متدرب",
                "verbose_name_plural": "المتدربون",
                "ordering": ["-started_day"],
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paymentdate",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "paymentCategry",
                    models.CharField(
                        choices=[
                            ("month", "شهرية"),
                            ("subscription", "انخراط"),
                            ("assurance", "التأمين"),
                            ("jawaz", "جواز"),
                        ],
                        max_length=20,
                        verbose_name="نوع الدفع",
                    ),
                ),
                (
                    "paymentAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="trainers.organizationinfo",
                        verbose_name="الجمعية",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="trainers.trainer",
                        verbose_name="المتدرب",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
                "ordering": ["-paymentdate"],
            },
        ),
        migrations.CreateModel(
            name="Emailed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="التاريخ والوقت"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "category",
                    models.CharField(
                        default="monthly", max_length=300, verbose_name="الفئة"
                    ),
                ),
                (
                    "sent_successfully",
                    models.BooleanField(default=True, verbose_name="تم الإرسال بنجاح"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="trainers.organizationinfo",
                        verbose_name="الجمعية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainers.trainer",
                        verbose_name="المتدرب",
                    ),
                ),
            ],
            options={
                "verbose_name": "بريد إلكتروني",
                "verbose_name_plural": "البريد الإلكتروني",
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="التاريخ"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "location",
                    models.CharField(
                        default="اركانة نجوم اركانة",
                        max_length=500,
                        verbose_name="المكان",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="المحتوى")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("League", "بطولة"),
                            ("training", "تدريب"),
                            ("dawri", "دوري"),
                            ("test", "امتحان"),
                            ("out", "خرجة"),
                            ("other", "اخرى"),
                        ],
                        max_length=30,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("local", "محلي"),
                            ("reigion", "جهوي"),
                            ("national", "وطني"),
                        ],
                        max_length=30,
                        verbose_name="النطاق",
                    ),
                ),
                (
                    "costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="التكاليف",
                    ),
                ),
                (
                    "participetion_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="سعر المشاركة",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="trainers.organizationinfo",
                        verbose_name="الجمعية",
                    ),
                ),
                (
                    "trainees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="trainers.trainer",
                        verbose_name="المتدربون",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقال",
                "verbose_name_plural": "المقالات",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TrainerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("بطاقة الوطنية", "بطاقة الوطنية"),
                            ("الحالة المدنية", "الحالة المدنية"),
                            ("وثيقة أخرى", "وثيقة أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الوثيقة",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="organizations/{instance.organization.slug}/trainees/documents/",
                        verbose_name="الملف",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="trainers.trainer",
                        verbose_name="المتدرب",
                    ),
                ),
            ],
            options={
                "verbose_name": "وثيقة متدرب",
                "verbose_name_plural": "وثائق المتدربين",
            },
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(
                fields=["organization", "is_active"],
                name="trainers_tr_organiz_9462ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(
                fields=["organization", "category"],
                name="trainers_tr_organiz_54bd64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payments",
            index=models.Index(
                fields=["organization", "paymentdate"],
                name="trainers_pa_organiz_6954a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payments",
            index=models.Index(
                fields=["trainer", "paymentCategry"],
                name="trainers_pa_trainer_1cf380_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainerdocument",
            unique_together={("trainer", "document_type")},
        ),
    ]
