# Generated by Django 5.1.4 on 2026-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationinfo",
            name="subscription_period",
            field=models.CharField(
                blank=True,
                choices=[("1m", "شهر واحد"), ("3m", "ثلاثة أشهر")],
                max_length=2,
                null=True,
                verbose_name="مدةالاشتراك",
            ),
        ),
    ]
