# Generated by Django 5.1.4 on 2026-01-05 21:16

from django.db import migrations,models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0002_alter_organizationinfo_subscription_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinfo",
            name="datepay",
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ دفع الايجار'),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="location",
            field=models.CharField(max_length=255, blank=True, verbose_name='الموقع')
        ),
    ]
